services:
  products:
    image: 'node:22'
    user: 'node'
    working_dir: /web
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/web
    command: 'node index.js'
    ports:
      - 4001:4001
