name: Algolia Publish

on:
  push:
    branches:
      - main

jobs:
  algolia-push-records:
    name: Push new records if changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: Build Packages
        run: pnpm build

      - name: Typecheck
        run: pnpm --filter website build

      - name: Algolia push
        run: pnpm --filter website algolia-sync
        env:
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          SITE_URL: https://www.graphql-yoga.com/

      - name: Format
        run: pnpm prettier

      - name: Compare
        run: git diff website/algolia-lockfile.json

      - name: Diff to file
        if: always()
        id: diff_result
        run: |
          OUTPUT=$(git diff website/algolia-lockfile.json)
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=result::$OUTPUT"

      - name: Commit algolia-lockfile.json
        if: always() && contains(steps.diff_result.outputs.result, 'diff')
        uses: EndBug/add-and-commit@v9
        with:
          commit: website/algolia-lockfile.json
          message: Update algolia-lockfile.json
          default_author: github_actions
