name: Canary Release

on:
  pull_request:
  workflow_dispatch:
    inputs:
      onDemand:
        description: 'Are you sure?'
        required: true
        default: 'yes'
      npmTag:
        description: 'NPM Tag'
        required: true
        default: 'alpha'
      npmVersionSuffix:
        description: 'Custom NPM Version Suffix'
        required: false

jobs:
  publish-canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event.inputs.onDemand == 'yes'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Get yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies using Yarn
        run: yarn

      - name: Setup NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Release Canary
        id: canary
        uses: 'kamilkisiela/release-canary@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          ON_DEMAND: ${{github.event.inputs.onDemand}}
          NPM_TAG: ${{github.event.inputs.npmTag || 'alpha'}}
          NPM_VERSION_SUFFIX: ${{github.event.inputs.npmVersionSuffix}}
        with:
          npm-token: ${{ secrets.NODE_AUTH_TOKEN }}
          npm-script: 'yarn release:canary'
          changesets: true

      - name: Publish a message
        if: steps.canary.outputs.released == 'true'
        uses: 'kamilkisiela/pr-comment@master'
        with:
          commentKey: canary
          message: |
            The latest changes of this PR are available as canary in npm (based on the declared `changesets`):

            ```
            ${{ steps.canary.outputs.changesetsPublishedPackages}}
            ```
          bot-token: ${{ secrets.GITHUB_TOKEN }}
          bot: 'github-actions[bot]'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish a empty message
        if: steps.canary.outputs.released == 'false'
        uses: 'kamilkisiela/pr-comment@master'
        with:
          commentKey: canary
          message: |
            The latest changes of this PR are not available as canary, since there are no linked `changesets` for this PR.
          bot-token: ${{ secrets.GITHUB_TOKEN }}
          bot: 'github-actions[bot]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
